apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment-blue
  labels:
    app: product-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service-blue
  template:
    metadata:
      labels:
        app: product-service-blue
    spec:
      containers:
      - name: product-service
        image: manojmovva/product-service:v1.0.0
        ports:
        - containerPort: 3002
