apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment-blue
  labels:
    app: user-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-blue
  template:
    metadata:
      labels:
        app: user-service-blue
    spec:
      containers:
      - name: user-service
        image: manojmovva/user-service:v1.0.0
        ports:
        - containerPort: 3001
        env:
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service-blue:3002"
