version: '3.8'
services:
  user-service:
    image: manojmovva/user-service:v2.0.0
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - PRODUCT_SERVICE_URL=http://192.168.49.2:30002

  product-service:
    image: manojmovva/product-service:v2.0.0
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
