version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3001:3001"
    networks:
      - ecommerce-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "3002:3002"
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
