apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment-green
  labels:
    app: product-service-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service-green
  template:
    metadata:
      labels:
        app: product-service-green
    spec:
      containers:
      - name: product-service
        image: manojmovva/product-service:v2.0.0
        ports:
        - containerPort: 3002
